In [25]:
import pandas as pd

data = {
    'Day': ['Tuesday.xlsx', 'Monday.xlsx', 'Thursday.xlsx', 'Monday.xlsx', 'Wednesday.xlsx',
            'Monday.xlsx', 'Wednesday.xlsx', 'Thursday.xlsx', 'Tuesday.xlsx'],
    'Time': ['02:30-03:50', '01:00-02:20', '01:00-02:20', '01:00-02:20', '01:00-02:20',
             '03:55-05:15', '03:55-05:15', '11:30-12:50', '11:30-12:50'],
    'Class': ['A-108', 'A-301', 'A-301', 'A-108', 'B-230', 'C-408', 'B-230', 'A-108', 'A-108'],
    'Subject': ['Fund of NLP (AI-JK)', 'PPIT (AI-J)', 'PPIT (AI-J)', 'Art Neural Net (AI-J)',
                'Art Neural Net (AI-J)', 'Info Sec (AI-J)', 'Info Sec (AI-J)', 'Game Theory (AI-JK)',
                'Game Theory (AI-JK)'],
}

df = pd.DataFrame(data)
df[['Start_Time', 'End_Time']] = df['Time'].str.split('-', expand=True)
df = df[['Day', 'Time', 'Class', 'Subject', 'Start_Time', 'End_Time']]
# df['Time'] = pd.to_datetime(df['Time'], format='%I:%M%p')

df['Start_Time'].tolist()

['02:30',
 '01:00',
 '01:00',
 '01:00',
 '01:00',
 '03:55',
 '03:55',
 '11:30',
 '11:30']

In [26]:
import re

def extract_numbers(input_string):
    # Use regex to find all numeric values in the string
    numbers = re.findall(r'\d+', input_string)
    return [int(number) for number in numbers]

# Example usage:
input_string = "The price of the product is $25 and the quantity is 10."
result = extract_numbers(input_string)
print(result)

[25, 10]

In [27]:
def format_time(time):
    hour = extract_numbers(time)[0]
    
    if hour >= 8 and hour < 12:
        return time + ' AM'
        
    else:
        return time + ' PM'

In [28]:
df['Start_Time'] = df['Start_Time'].apply(format_time)
df['End_Time'] = df['End_Time'].apply(format_time)

df

,Day,Time,Class,Subject,Start_Time,End_Time
0,Tuesday.xlsx,02:30-03:50,A-108,Fund of NLP (AI-JK),02:30 PM,03:50 PM
1,Monday.xlsx,01:00-02:20,A-301,PPIT (AI-J),01:00 PM,02:20 PM
2,Thursday.xlsx,01:00-02:20,A-301,PPIT (AI-J),01:00 PM,02:20 PM
3,Monday.xlsx,01:00-02:20,A-108,Art Neural Net (AI-J),01:00 PM,02:20 PM
4,Wednesday.xlsx,01:00-02:20,B-230,Art Neural Net (AI-J),01:00 PM,02:20 PM
5,Monday.xlsx,03:55-05:15,C-408,Info Sec (AI-J),03:55 PM,05:15 PM
6,Wednesday.xlsx,03:55-05:15,B-230,Info Sec (AI-J),03:55 PM,05:15 PM
7,Thursday.xlsx,11:30-12:50,A-108,Game Theory (AI-JK),11:30 AM,12:50 PM
8,Tuesday.xlsx,11:30-12:50,A-108,Game Theory (AI-JK),11:30 AM,12:50 PM

In [29]:
# Assuming 'Time' is the column containing time in 12-hour format without AM/PM
# Convert 'Time' to datetime objects
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='%I:%M %p')

# Sort the DataFrame by the 'Time' column
df_sorted = df.sort_values(by='Start_Time')
df_sorted

,Day,Time,Class,Subject,Start_Time,End_Time
7,Thursday.xlsx,11:30-12:50,A-108,Game Theory (AI-JK),1900-01-01 11:30:00,12:50 PM
8,Tuesday.xlsx,11:30-12:50,A-108,Game Theory (AI-JK),1900-01-01 11:30:00,12:50 PM
1,Monday.xlsx,01:00-02:20,A-301,PPIT (AI-J),1900-01-01 13:00:00,02:20 PM
2,Thursday.xlsx,01:00-02:20,A-301,PPIT (AI-J),1900-01-01 13:00:00,02:20 PM
3,Monday.xlsx,01:00-02:20,A-108,Art Neural Net (AI-J),1900-01-01 13:00:00,02:20 PM
4,Wednesday.xlsx,01:00-02:20,B-230,Art Neural Net (AI-J),1900-01-01 13:00:00,02:20 PM
0,Tuesday.xlsx,02:30-03:50,A-108,Fund of NLP (AI-JK),1900-01-01 14:30:00,03:50 PM
5,Monday.xlsx,03:55-05:15,C-408,Info Sec (AI-J),1900-01-01 15:55:00,05:15 PM
6,Wednesday.xlsx,03:55-05:15,B-230,Info Sec (AI-J),1900-01-01 15:55:00,05:15 PM